[pytest]
testpaths = tests
norecursedirs = .git .hg .svn .tox .nox .venv venv env build dist node_modules __pycache__ pytest-cache-files-*
filterwarnings =
    ignore::starlette.exceptions.StarletteDeprecationWarning
addopts = -p no:cacheprovider --basetemp=tests/.pytest-tmp
